### ISSUE TITLE
Traefik Configuration

### ISSUE THREAD

**Issue by slash5k1** [syncthing/docs#893]
Not a bug but a thank you to the good work published in the PR [https://github.com/syncthing/docs/pull/684](https://github.com/syncthing/docs/pull/684) where I was able to get traefik to proxy the discovery service.

example compose file:
```
  syncthing-discosrv:
    image: syncthing/discosrv:1.29
    container_name: syncthing-discosrv
    volumes:
      - syncthing-discover:/var/stdiscosrv
    ports:
      - 8880:8443
    restart: unless-stopped
    entrypoint: ["/bin/stdiscosrv", "--http", "--debug"]
```

example traefik file:
```
http:
  routers:
    syncthing-discovery-router:
      rule: Host(`syncthing-discovery.example.com`)
      service: syncthing-discovery-service
      entryPoints:
      - websecure
      tls:
        options: syncthing-discosrv
      middlewares:
        - syncthing-discovery-headers
  services:
    syncthing-discovery-service:
      loadBalancer:
        servers:
        - url: http://10.0.0.10:8880
  middlewares:
    syncthing-discovery-headers:
      passtlsclientcert:
        pem: true
tls:
  options:
    syncthing-discosrv:
      clientAuth:
#       clientAuthType: RequireAnyClientCert # this was the example in the PR however i found the option below to work
        clientAuthType: RequestClientCert
  certificates:
  - certFile: /etc/traefik/ssl/example.com.crt
    keyFile: /etc/traefik/ssl/example.com.key
```

Hopefully this will help others and maybe the devs will publish the traefik config into the documentation
