### ISSUE TITLE
Improve discosrv documentation for debugging

### ISSUE THREAD

**Issue by mcx808** [syncthing/docs#918]
I'm having a hard time debugging a Discovery Server install. 

It's behind a Caddy proxy so I've implemented the required directives as

**Comment by mcx808** [comment]
### Update

Ok, I found when browsing issue https://github.com/syncthing/docs/issues/893 that syncthing/discosrv:v2 continers are maintained by syncthing, which isn't mentioned anywhere in the documentation.
In order to rule out any issues with my container build from alpine, I ran this version instead, and it seems to work. Here's my compose file:

```
services:
  stdiscosrv:
    image: syncthing/discosrv:v2
    container_name: syncthing-discovery
    restart: always
    networks:
      - services
    entrypoint: ["/bin/stdiscosrv", "--http", "--debug"]
networks:
  services:
    external: true
``` 

I'm still frustrated by the lack of documentation though. The console now shows that this is `stdiscosrv v2.0.0-beta.10.dev.11.gabe34fc1-v2` but seems to be the latest version tag that's not a beta? But it was updated 17 hours ago as of today, so is this solution not fully maintained?
